# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25b2073d58a8ed38bbe232583f96c784d77714ad83cbe11f0fc9873cf8408c7cf96d6fae77934f7af602d928fe417a98c320acb1d9d6355946bac33c40e306e

test:
  secret_key_base: 575e9b90e74356a2c4ab476583230dbe334a9a887c4b3db9970c63617e153473724ef6136a8d4264d55baa37112c19eee439c874887d5a6ab09aee26082d484b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
